### ISSUE TITLE
解除网页限制的屏蔽列表好像无法使用了

### ISSUE THREAD

**Issue by DeepChirp** [rxliuli/userjs#14]
具体表现为，屏蔽列表无法更新；将Github上的列表复制到脚本的存储中无法使用

**Comment by rxliuli** [comment]
> 具体表现为，屏蔽列表无法更新；将 Github 上的列表复制到脚本的存储中无法使用

这个可能是需要代理的问题，之前加了 cdn，后面又删掉了。。。

**Comment by rxliuli** [comment]
最新版本已经重新使用了 cdn
