### ISSUE TITLE
https://qiangwaikan.com/vpn-vs-proxy/ 该网站无法复制

### ISSUE THREAD

**Issue by lyjhyjyes** [rxliuli/userjs#15]
https://qiangwaikan.com/vpn-vs-proxy/
防复制太强，多次尝试无法复制

**Comment by rxliuli** [comment]
吾辈测试了下是可以的，你是 PC 网页么？

lyjhyjyes <notifications@github.com> 于 2020年8月30日周日 下午5:17写道：

**Comment by lyjhyjyes** [comment]
我是win10 chrome改版，非官方版本。pc网页上，解除限制，恢复默认，都无法复制

**Comment by rxliuli** [comment]
不处理 chrome/Firefox 之外的兼容性

lyjhyjyes <notifications@github.com> 于 2020年8月31日周一 下午2:22写道：
