### ISSUE TITLE
解除网页限制：配置面板”清空“、”更新“无效或延迟

### ISSUE THREAD

**Issue by Erbzur** [rxliuli/userjs#16]
脚本：解除网页限制

问题：配置面板点击”清空“或”更新“按钮，显示成功后刷新，配置没有变化，反复刷新多次后可能会显示。

环境：Windows 10, Chromium 80.0.3987.163, Tempermonkey 4.11.

**Comment by rxliuli** [comment]
可否发一下控制台的信息？

![image](https://user-images.githubusercontent.com/24560368/96072212-6712af00-0ed6-11eb-8940-8ef719031d1b.png)

**Comment by Erbzur** [comment]
一、点击清空：
![image](https://user-images.githubusercontent.com/39868528/96072786-a42b7100-0ed7-11eb-81b6-73f89e50ba3c.png)

第一次刷新页面：
![image](https://user-images.githubusercontent.com/39868528/96072826-bd342200-0ed7-11eb-9912-1bc37142246c.png)

第二次刷新：
![image](https://user-images.githubusercontent.com/39868528/96072854-ce7d2e80-0ed7-11eb-9c71-e32a4a5cb8a3.png)

重复上述操作出现：
![image](https://user-images.githubusercontent.com/39868528/96072941-fa98af80-0ed7-11eb-8780-e4893978aa8e.png)

看控制台，清空逻辑可能触发了更新，从而使清空无效。手动删除所有规则，刷新后不会无效：
![image](https://user-images.githubusercontent.com/39868528/96073159-7a267e80-0ed8-11eb-81e9-fc68f01fe0bf.png)

二、点击更新：
![image](https://user-images.githubusercontent.com/39868528/96073216-99251080-0ed8-11eb-832b-82df394e3ca0.png)

更新成功后刷新：
![image](https://user-images.githubusercontent.com/39868528/96073246-ab06b380-0ed8-11eb-8a47-3fd708884aaa.png)
可以看到，配置列表仍为空。

此后刷新若干次后仍无结果，反而点击清空后更新了列表：
![image](https://user-images.githubusercontent.com/39868528/96073497-25cfce80-0ed9-11eb-8671-1577f32b8f01.png)
![image](https://user-images.githubusercontent.com/39868528/96073525-31bb9080-0ed9-11eb-916a-055d881427e4.png)

**Comment by rxliuli** [comment]
尝试你是否能访问 https://userjs.rxliuli.com/blockList.json

**Comment by Erbzur** [comment]
可以访问
![image](https://user-images.githubusercontent.com/39868528/96074151-8b708a80-0eda-11eb-9279-9866595e927f.png)

**Comment by rxliuli** [comment]
晚点我看一下，可能是由于国外 cdn 被劣化导致的网络延迟

**Comment by rxliuli** [comment]
我更新了一下，已修复两个问题
清空会导致刷新的问题已修复，原因是更新后将最后更新时间的 flag 也删除了
更新没有生效，同样是因为更新时间 flag 的原因，在没有满足条件时没有真的更新

**Comment by rxliuli** [comment]
ref: https://github.com/rxliuli/userjs/commit/d447e351090734b17ecdbccbedceb1f8643cfbc1
