### ISSUE TITLE
创世中文网

### ISSUE THREAD

**Issue by DeepChirp** [rxliuli/userjs#23]
您好！
复制创世中文网上面的文章时，复制出来的文章每一句都有文字空缺
测试链接：http://chuangshi.qq.com/bk/xh/AGkEMF1pVj4APVRmATABYw-r-1.html

**Comment by rxliuli** [comment]
因为网站使用了自定义的字体，所以复制出来在其他字体下会出现乱码
![image](https://user-images.githubusercontent.com/24560368/114289667-69804b00-9aac-11eb-9db3-df53294cea7c.png)

具体原理参考：[防爬虫 - 利用自定义字体实现数据防采集](https://www.jianshu.com/p/01fe429884f9)
这超出了这个脚本所拥有的能力，如果需要应该创造一个专门针对这个网站的油猴脚本，所以吾辈不会解决这个问题
