### ISSUE TITLE
道客巴巴

### ISSUE THREAD

**Issue by DeepChirp** [rxliuli/userjs#25]
您好！
该功能实现可能有点困难。我在审查元素里面看了一下，这些文字都是加密的，并且选中文字时，并没有真正选中。该网页可能需要单独支持，不知道能否做到

**Comment by rxliuli** [comment]
和之前创世中文网是同一个问题，参考：https://github.com/rxliuli/userjs/issues/23。
当然，如果想做的话也可以做到，大体上有两个思路

1. 找到加密文字与解密文字的映射规则，一般是一个网页自定义字体
2. 使用 OCR 技术

不过这超出了网页接触屏蔽这个脚本的范围

**Comment by rxliuli** [comment]
看了一下，这个网站使用的 canvas 画布，所见文字并不是文字，本质上都是由这个网站的开发者自行“画”上去的，所以如果想要破解无法复制的问题只能使用 OCR 技术。

![image](https://user-images.githubusercontent.com/24560368/114745110-ef3c1900-9d80-11eb-96fa-b49f421f1ce9.png)

**Comment by rxliuli** [comment]
如果需要下载文档，参考：https://zhuanlan.zhihu.com/p/114246245

**Comment by DeepChirp** [comment]
您好！
感谢您的回复
我看到这个脚本才想到提出这个issue的https://greasyfork.org/zh-CN/scripts/405130-%E6%96%87%E6%9C%AC%E9%80%89%E4%B8%AD%E5%A4%8D%E5%88%B6
另外请问一下，百度文库也是同理吗？直接检查元素好像可以直接看到文字

**Comment by rxliuli** [comment]
> 我看到这个脚本才想到提出这个 issue 的 https://greasyfork.org/zh-CN/scripts/405130-%E6%96%87%E6%9C%AC%E9%80%89%E4%B8%AD%E5%A4%8D%E5%88%B6

你提到的这个脚本是自行实现的**复制**功能，这里则是取消了网站的一些 hack 事件，相关原理及吾辈的选择在这里有提及：https://blog.rxliuli.com/p/9bbb456a93a8410e9d2313dcd20dc07c/
