### ISSUE TITLE
屏蔽复制粘贴的配置页面无法新增

### ISSUE THREAD

**Issue by rxliuli** [rxliuli/userjs#30]
看起来像是 user.js 没有暴露出这个变量

![image](https://user-images.githubusercontent.com/24560368/115965188-7b58f800-a55a-11eb-8a18-9a0204c2471d.png)

**Comment by DeepChirp** [comment]
![动画](https://user-images.githubusercontent.com/66902050/115965499-1e5e4180-a55c-11eb-8d54-a277169d942c.gif)
haolY(^o^)Y
现在已经修好了

**Comment by DeepChirp** [comment]
@rxliuli 这个Bug好像又出现了 xd

**Comment by shenzhiming88** [comment]
@rxliuli 您好！
![image](https://user-images.githubusercontent.com/66902050/126805185-7f049a9b-b322-46b6-a15d-164328f52f16.png)
