### ISSUE TITLE
www.bimiacg.net

### ISSUE THREAD

**Issue by DeepChirp** [rxliuli/userjs#38]
您好！
这个域名好像不太好处理呀
实例链接：`http://www.bimiacg.net/bangumi/bi/3486`
能解除屏蔽，但是如果把整个域名添加进去的话，视频右键又会受到影响
先反馈给ublock吧
![image](https://user-images.githubusercontent.com/66902050/124358725-291c0d80-dc54-11eb-9237-9a2eb879ce4b.png)

**Comment by rxliuli** [comment]
是的，目前所有功能是默认全部开启的，之前有考虑过允许通过配置针对网站启用部分功能，但感觉对用户而言更加复杂的配置有点太麻烦了，故而没有实现。。。如果要实现复杂配置的话，那可能会连之前的删除透明遮罩也做成配置了
