### ISSUE TITLE
部分网页屏蔽开发者工具

### ISSUE THREAD

**Issue by DeepChirp** [rxliuli/userjs#39]
ref: https://greasyfork.org/zh-CN/scripts/391193-%E8%A7%A3%E9%99%A4%E7%BD%91%E9%A1%B5%E9%99%90%E5%88%B6/discussions/91849#comment-215477
是否需要在脚本内添加对此类限制的屏蔽呢？

**Comment by rxliuli** [comment]
不会，这超越了这个脚本的目标范围
