### ISSUE TITLE
某些网页会禁用开发者工具

### ISSUE THREAD

**Issue by mxdh** [rxliuli/userjs#40]
与 https://greasyfork.org/zh-CN/scripts/391193-%E8%A7%A3%E9%99%A4%E7%BD%91%E9%A1%B5%E9%99%90%E5%88%B6/discussions/91849 相同

https://businessnews.in/wp-content/plugins/ungrabber/js/devtools-detect.min.js?ver=3.0.3

https://businessnews.in/wp-content/plugins/ungrabber/js/ungrabber.min.js?ver=3.0.3

https://businessnews.in/wp-content/plugins/ungrabber/js/hotkeys.min.js?ver=3.0.3

这几个js除了会拦截右键和复制外（这个脚本可以解决），还会拦截f12和一堆快捷键，检测开发者工具是否存在（似乎是通过页面大小）。

作者大大有空可以看一下吗？

**Comment by mxdh** [comment]
已经报给UBO了，就是不知道他们收不收。

https://github.com/uBlockOrigin/uAssets/issues/9536

**Comment by mxdh** [comment]
他们收了
还是谢谢作者大大

**Comment by DeepChirp** [comment]
您好！
这个issue重复了：https://github.com/rxliuli/userjs/issues/39 ，昨天看到了就顺便提交了一下
另外这种ublock都会收到`uBlock filters – Annoyances`屏蔽列表中的
