### ISSUE TITLE
红薯网

### ISSUE THREAD

**Issue by DeepChirp** [rxliuli/userjs#48]
您好！
https://www.hongshu.com/content/100102/175883-999.html
该网页似乎使用特殊字符，所以无法正常复制，您觉得要不要将这个域名从屏蔽列表中删除？
![image](https://user-images.githubusercontent.com/66902050/128843193-cb39dff5-b2a4-4bf0-9c0e-3e172ba0c950.png)

**Comment by rxliuli** [comment]
那就删除了吧，最近实在是工作忙的没时间修了（而且这种特殊字符也无法通用化处理）

**Comment by DeepChirp** [comment]
@rxliuli 好的，我已经发布了，但是好像存在一个问题
好像用`yarn docs:deploy`和`yarn deploy`都会报错，不知道为什么
![image](https://user-images.githubusercontent.com/66902050/128848010-99c104ff-06f9-4bb1-aab0-fe5c522fbd4b.png)

**Comment by rxliuli** [comment]
先运行 yarn 安装依赖

**Comment by DeepChirp** [comment]
> 先运行 yarn 安装依赖

您好！
之前已经使用`yarn install`安装好了，又试了一遍，结果还是这样的，不知道为什么

**Comment by rxliuli** [comment]
> > 先运行 yarn 安装依赖
> 
> 您好！
> 之前已经使用 `yarn install` 安装好了，又试了一遍，结果还是这样的，不知道为什么

额，使用 `yarn build && yarn deploy` 就好了（抱歉，上周末删除了一些脚本，也对现有脚本做了一些修改）
