### ISSUE TITLE
脚本发布的建议

### ISSUE THREAD

**Issue by DeepChirp** [rxliuli/userjs#49]
您好！
能否将脚本发布在jsDelivr上，方便国内用户安装脚本？谢谢

**Comment by rxliuli** [comment]
可以使用形如 <https://userjs.rxliuli.com/goflac-download/index.user.js> 的 url 安装，userjs.rxliuli.com 使用 cloudflare 作为 cdn，国内应该可以正常访问到

**Comment by rxliuli** [comment]
可能吾辈需要修改 README 中的地址

**Comment by DeepChirp** [comment]
@rxliuli 抱歉，我好像把别的文件也修改了

**Comment by rxliuli** [comment]
> @rxliuli 抱歉，我好像把别的文件也修改了

哦，看起来像是 yarn 自动更新了。。。没什么大问题
