### ISSUE TITLE
知识星球复制不了，恳求大佬挑战它~

### ISSUE THREAD

**Issue by mr-dragon** [rxliuli/userjs#5]
https://wx.zsxq.com/
开启后剪切板内容变成：本星球已开启内容保护，无法复制主题内容
右键复制也是如此~

之前试过微信阅读的用其他脚本可以解除，但是是乱码的(无规则且很多有符号)，这个估计无解

**Comment by rxliuli** [comment]
抱歉，之前没看到，等会吾辈去看一下

**Comment by rxliuli** [comment]
> https://wx.zsxq.com/
> 开启后剪切板内容变成：本星球已开启内容保护，无法复制主题内容
> 右键复制也是如此～
> 
> 之前试过微信阅读的用其他脚本可以解除，但是是乱码的 (无规则且很多有符号)，这个估计无解

无法测试，可否私一下账号、或者免费的文章链接可供测试？

**Comment by rxliuli** [comment]
很久没有回复，暂时关闭了。。。

**Comment by bigonestep** [comment]
一样遇到这个问题，如果有需要，我这边可以帮忙扫码进入，供测试。

**Comment by rxliuli** [comment]
> 一样遇到这个问题，如果有需要，我这边可以帮忙扫码进入，供测试。

有 telegram 或 email 可以发给你么？吾辈使用的是 rxliuli@gmail.com

**Comment by bigonestep** [comment]
可以的，你那边打开知识星球然后选择微信扫码登录，把二维码截图发我就可以了。

**Comment by rxliuli** [comment]
> 可以的，你那边打开知识星球然后选择微信扫码登录，把二维码截图发我就可以了。

![image](https://user-images.githubusercontent.com/24560368/98822177-75b79c00-246b-11eb-8c6e-c56a2c8de755.png)

**Comment by bigonestep** [comment]
我的telegram：touch_README

**Comment by rxliuli** [comment]
这是一个已知问题，chrome 之外的浏览器不保证生效，即便是同一个内核的浏览器（包括 Edge、360 等）亦然
