### ISSUE TITLE
feat: 支持解除屏蔽 `beforepaste/onbeforecopy/onbeforecut/onbeforexrselect` 事件（似乎是 chrome 限定）

### ISSUE THREAD

**Issue by 55free** [rxliuli/userjs#50]
mooc网阻止粘贴的方式是
answerEditor.addListener('beforepaste', myEditor_paste);
脚本阻止无效

**Comment by rxliuli** [comment]
吾辈更新了脚本，你可以试一下么？如果可以，吾辈将发布新版本

[index.user.zip](https://github.com/rxliuli/userjs/files/7169364/index.user.zip)

**Comment by 55free** [comment]
![image](https://user-images.githubusercontent.com/49394536/133422206-f8bd6a74-1350-4a84-8fb6-f92f6dc141fd.png)
没有起作用

**Comment by 55free** [comment]
![image](https://user-images.githubusercontent.com/49394536/133422539-d5519bd7-11bd-46e0-9aff-03b2e37839a4.png)
mousedown 能拦截
paste 不行

**Comment by rxliuli** [comment]
请发送具体网页的 url

**Comment by 55free** [comment]
这是 超星mooc 学生用的

**Comment by rxliuli** [comment]
如果需要认证，请将认证发送至吾辈的 email 邮箱，吾辈需要复现，无法复现很难定位具体问题

**Comment by 55free** [comment]
留js文件
[doHomeWorkNew.txt](https://github.com/rxliuli/userjs/files/7169534/doHomeWorkNew.txt)

**Comment by 55free** [comment]
如果还是不行 会发学生认证

**Comment by rxliuli** [comment]
这个问题核心是因为油猴脚本加载晚了，单从油猴脚本的层面而言似乎无法解决，但或许有其他解决方案 -- 例如使用 chrome 插件或 puppeteer 获得更多的控制权，参考：<https://developer.chrome.com/docs/extensions/mv3/content_scripts/#run_time>

![image](https://user-images.githubusercontent.com/24560368/133425716-f033b885-9e93-4d13-8d61-f9b392ed6e93.png)

---

这里提供一个思路是拦截网络请求，改写浏览器接收到的 html，替换其中 js 部分的代码，将事件监听的代码全部删除或置空

**Comment by shenzhiming88** [comment]
@rxliuli 用uBO不知道是否可行，或许可以向他们反馈一下
