### ISSUE TITLE
添加Actions以便自动同步屏蔽列表

### ISSUE THREAD

**Issue by DeepChirp** [rxliuli/userjs#51]
这样做可能会增加一些维护成本，但是可以更加方便。不知道您是否有这个想法呢？

**Comment by rxliuli** [comment]
感觉使用 github actions 发布 github pages 很麻烦，之前尝试对 blog 做这个配置的时候尝试过，而且 github actions 调试。。。没法调试，只能一次次提交上来看效果

**Comment by rxliuli** [comment]
另外最近的更新已重新构建并推送

**Comment by DeepChirp** [comment]
> 另外最近的更新已重新构建并推送

好的，谢谢您。我对这方面没有经验，只是提供一个设想。

另外屏蔽列表好像还是没有推送上去。

**Comment by rxliuli** [comment]
抱歉，看错模块了，现在已推送，参考：https://github.com/rxliuli/userjs/commit/187b6224c56acba2ad778a2f97126518d7d7b793#diff-d01cc83e3af3e0f272725a6e1bba9a75a8e9c3d1250ece86df05d35d293c218bR126
