### ISSUE TITLE
12315.cn 可以加入默认配置内

### ISSUE THREAD

**Issue by iamvicliu** [rxliuli/userjs#52]
提交反馈和投诉时，所有输入框都禁止粘贴

**Comment by DeepChirp** [comment]
感谢反馈
@rxliuli 可能还要麻烦您推送一下，太久没有推送，忘记了 xd

**Comment by rxliuli** [comment]
> 感谢反馈 @rxliuli 可能还要麻烦您推送一下，太久没有推送，忘记了 xd

稍等

**Comment by rxliuli** [comment]
> > 感谢反馈 @rxliuli 可能还要麻烦您推送一下，太久没有推送，忘记了 xd
> 
> 稍等

已发布
