### ISSUE TITLE
MDN 更新样式后，自动跳转中文页面失效了

### ISSUE THREAD

**Issue by kahosan** [rxliuli/userjs#55]
看了下，包含语言选项的元素被隐藏了，我只能想到先 `click()` 一下 `button` 元素，获取到语言列表之后和原来一样跳转。
大佬有什么好的办法嘛？

**Comment by rxliuli** [comment]
两个思路

1. 查询 dom 元素，找到隐藏的语言选项的内容（或者拦截 ajax 请求）
2. 设置语言选项的弹窗样式隐藏，然后触发点击，最后获取语言选项

**Comment by rxliuli** [comment]
已使用第一种方式支持新版 mdn，请更新测试

https://github.com/rxliuli/userjs/commit/612b137d5afdb4d60aef1aec7c9a4935d164cddf

**Comment by kahosan** [comment]
可以正常使用了，谢谢
