### ISSUE TITLE
315网站不支持粘贴

### ISSUE THREAD

**Issue by cantonadong** [rxliuli/userjs#8]
http://www.12315.cn/cuser/portal/tscase/information

**Comment by rxliuli** [comment]
> http://www.12315.cn/cuser/portal/tscase/information

这个网站必须先登录呢，可以用账户密码测试一下么？

**Comment by rxliuli** [comment]
> http://www.12315.cn/cuser/portal/tscase/information

抱歉，GitHub 没发邮件给吾辈所以没看到。。。
